# sample_broker_config.yml

broker:
  hostname: "localhost"
  port: 5555
  # Olympus frontend server
  frontend_server:
    hostname: "localhost"
    port: 5556
  # Oracle backend client
  backend_client:
    hostname: "localhost"
    port: 8081